car_owner/urls.py
from django.urls import path
from .views import CarUpdateView 
from . import views


urlpatterns = [
    path("dash/", views.dashboard, name="dash"),
    path("car_add/", views.car_add, name="car_add"),
    path("profile/add/", views.add_profile, name="add_profile"),
    path("cars/<int:pk>", views.delete_car, name="delete_car"),
    path("edit/<int:pk>", CarUpdateView.as_view()),
]

car_rental/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from home.views import (
    landingpage
)

urlpatterns = [
    path('', landingpage, name='landingpage'),
    path('', include("cars.urls")),
    path('', include("chauffeur.urls")),
    path('', include("rental.urls")),
    path('', include("car_owner.urls")),
    path('', include("user.urls")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path, include
from .views import UpdateCarLikes
from . import views

urlpatterns = [
    path("car_list/", views.all_cars, name="car_list"),
    path("car/<int:pk>/", views.car_detail, name="car_detail"),
    path("photo/<int:pk>/", views.photo, name="photo"),
    path("car/<int:pk>/save/", views.save_car, name="save-car"),
    path("saved_car_list/", views.user_saved_cars, name="saved-cars"),
    path("car/<int:pk>/remove/", views.remove_car, name="remove-car"),
    path(
        "car_review/<int:car_id>/<str:review>",
        UpdateCarLikes.as_view(),
        name="car_review",
    ),
    path("car/<int:car_id>/remove/", views.remove_car, name="remove_from_saved"),
    path("index/", views.index, name="index"),
    path("search_cars/", views.search_cars, name="search_cars"),
    path("filter_car/", views.car_filter, name="car-filter"),
]

cars/models.py
from django.db import models
from django.shortcuts import reverse
from decimal import Decimal
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from user.models import CustomUser
from django.utils import timezone


def daily_rental_cost(value):
    if value <= 0:
        raise ValidationError(
            _(f"{value} is to small, it must be greater than 0"),
            params={"value": value},
        )


def validate_num_of_passengers(value):
    if value > 8:
        raise ValidationError(
            _(f"{value} is too much passengers, it must be less than 8"),
            params={"value": value},
        )


def car_photo_upload_path(instance, filename):
    return f"static/media/cars/{instance.owner.username}/{filename}"


class Car(models.Model):
    categories = [
        ("Petrol", "Petrol"),
        ("Diesel", "Diesel"),
        ("Gas", "Gas"),
        ("Hybrib", "Hybrid"),
        ("Electric", "Electric"),
    ]

    id = models.AutoField(null=False, primary_key=True)
    image = models.ImageField(
        upload_to="static/media/cars/images",
        blank=False,
        default="/static/media/cars/images/logo.png",
    )
    owner = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True, blank=False
    )
    make = models.CharField(max_length=50, null=False, blank=False)
    car_model = models.CharField(max_length=20, null=False, blank=False)
    city = models.CharField(max_length=100, null=True, blank=False)
    residence = models.CharField(max_length=100, null=True, blank=False)
    model_year = models.IntegerField(default=0)
    color = models.CharField(max_length=20, blank=False)
    num_seats = models.PositiveSmallIntegerField(
        null=False, blank=False, validators=[validate_num_of_passengers]
    )
    capacity = models.CharField(max_length=100)
    plate_number = models.CharField(max_length=7, blank=False)
    is_booked = models.BooleanField(default=False)
    has_tracker = models.BooleanField(default=False)
    daily_rental_price = models.DecimalField(
        decimal_places=2,
        max_digits=6,
        default=Decimal("0.00"),
        validators=[daily_rental_cost],
    )
    late_return_fee_per_hr = models.DecimalField(
        max_digits=5, decimal_places=2, default=Decimal("0.00"), null=True, blank=True
    )
    ecocash_rate = models.DecimalField(
        max_digits=5, decimal_places=2, default=Decimal("0.00"), null=True, blank=True
    )
    mileage = models.PositiveIntegerField(null=True, blank=True)
    fuel_type = models.CharField(max_length=10, choices=categories)
    like = models.IntegerField(default=0)
    description = models.CharField(max_length=500, null=True, default=None)
    created_at = models.DateTimeField(default=timezone.now)
    is_saved = models.BooleanField(default=False)

    def get_total_likes(self):
        return self.likes.users.count()

    def get_total_dis_likes(self):
        return self.dis_likes.users.count()

    def __str__(self):
        return self.make

    def get_url(self):
        return reverse("car_detail", args=(self.id))

    # def get_image(self, index=0):
    #   if index < len(self.image):
    #      return self.image[index]
    # else:
    #    return None


class SavedCar(models.Model):
    car = models.ForeignKey(Car, related_name="cars", on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, related_name="saved", on_delete=models.CASCADE)
    date_saved = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ("user", "car")

    def __str__(self):
        return self.car.make


class Like(models.Model):
    """like  car"""

    car = models.OneToOneField(Car, related_name="likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(CustomUser, related_name="requirement_car_likes")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.car.make)[:30]


class DisLike(models.Model):
    """Dislike  car"""

    car = models.OneToOneField(Car, related_name="dis_likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(CustomUser, related_name="requirement_car_dis_likes")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.car.make)[:30]

car_owner/forms.py
import re
from django import forms
from user.models import UserProfile
from cars.models import Car
from django.core.exceptions import ValidationError



class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        exclude = ["id", "owner", "is_booked", "capacity", "like"]
        fields = [
            "image",
            "make",
            "car_model",
            "daily_rental_price",
            "late_return_fee_per_hr",
            "ecocash_rate",
            "plate_number",
            "mileage",
            "model_year",
            "fuel_type",
            "color",
            "num_seats",
            "description",
        ]

car_owner/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from cars.models import Car
from chauffeur.models import Chauffeur
from .forms import CarForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DeleteView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from user.models import UserProfile
from django.contrib import messages


def car_add(request):
    if request.method == "POST":
        form = CarForm(request.POST, request.FILES)
        if form.is_valid():
            car = form.save(commit=False)
            car.owner = request.user
            car.save()
            messages.success(request, "Car added successfully")
            return redirect("dash")
    else:
        form = CarForm()
    return render(request, "car_owner/car_add.html", {"form": form})


@login_required
def delete_car(request, pk):
    car = Car.objects.get(pk=car.pk, owner=request.user)
    if request.method == "POST":
        car.delete()
    return redirect("dash")


def dashboard(request):
    cars = Car.objects.filter(owner=request.user)
    # rentals = Rental.objects.filter(car__in=cars).order_by('-id')
    context = {"cars": cars}
    return render(request, "car_owner/dashboard.html", context)


class CarUpdateView(LoginRequiredMixin, UpdateView):
    model = Car
    form_class = CarForm
    template_name = "car_owner/car_update.html"
    success_url = reverse_lazy("dash")



# Multi image approach

# class UploadView(FormView):
#   form_class = CarForm
#  template_name = 'car_owner/dashboard.html'
# success_url = reverse_lazy('dashboard')

# def form_valid(self, form):
#    car = form.save(commit=False)
#   car.owner = self.request.user
#  car.save()

# image_files = self.request.FILES.getlist('image')
# if isinstance(image_files, list):
#   for image_file in image_files:
#      ext = os.path.splitext(image_files.name)[1]
#     allowed_extensions = ['.jpg', '.jpeg', '.png', '.gif']
#    if ext.lower() not in allowed_extensions:
#       raise ValidationError("File type not supported.")
#  CarImage.objects.create(car=car, image=image_file)
# else:
#   image_file = image_files
#  ext = os.path.splitext(image_file)[1]
# allowed_extensions = ['.jpg', '.jpeg', '.png', '.gif']
# if ext.lower() not in allowed_extensions:
#   raise ValidationError("File type not supported.")
# CarImage.objects.create(car=car, image=image_file)
# context = self.get_context_data()
# context['car'] = car

# return super().form_valid(form)

car_owner/templates/add_profile.html
<!-- add_profile.html -->
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
      {{ form.profile_pic.label_tag }}
      {{ form.profile_pic }}
    </div>
    <div class="form-group">
      {{ form.phone_number.label_tag }}
      {{ form.phone_number }}
    </div>
    <div class="form-group">
      {{ form.city.label_tag }}
      {{ form.city }}
    </div>
    <div class="form-group">
      {{ form.address.label_tag }}
      {{ form.address }}
    </div>
    <button type="submit" class="btn btn-primary">Save Profile</button>
  </form>

car_owner/templates/car_add.html
{% extends 'base.html' %}
{% block content %}

<style>
    div#car_add {
        padding-top: 3em;
        padding-bottom: 12em;
     }
</style>

<link rel="stylesheet" href="/static/css/car_add.css">
<body>
<div id="car_add" class="row justify-content-center">
    <div class="col-md-8">
        <div class="card-header">
            <h4 class="card-title">Add Car</h4>
        </div>
  
        {% for message in messages %}
            <p id="messages">{{message}}</p>
        {% endfor %}

        <div class="card-body">
            <form method="POST" action="{% url 'car_add' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                
                    <div class="form-group imagefield col-md-6">
                        <label for="image"></label>
                        <div class="puput">
                        <input type="file" name="image" id="image" placeholder="Car Photo" class="form-control-file" accept="image/*" onchange="previewCarPhoto(event)">
                        </div>
                        <img src="#" alt="Car Photo Preview" class="car-preview img-thumbnail" id="car-photo-preview" style="display: none">
                    </div>

                        <div class="form-group col-md-6">
                            <label for="make"></label>
                            <input type="text" name="make" id="make" maxlength="50" placeholder="Make" class="form-control" required>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="car_model"></label>
                            <input type="text" name="car_model" id="car_model" placeholder="Car Model" class="form-control" required>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="daily_rental_price"></label>
                            <input type="number" name="daily_rental_price" id="daily_rental_price" step="0.01"  maxlength="50" placeholder="Daily Rental Price" class="form-control" required>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="late_return_fee_per_hr"></label>
                            <input type="number" name="late_return_fee_per_hr" id="late_return_fee_per_hr" step="0.01" placeholder="Late Return Fee/Hour" class="form-control" required>
                        </div>
               
                        <div class="form-group col-md-6">
                            <label for="ecoacash_rate"></label>
                            <input type="number" name="ecoacash_rate" id="ecoacash_rate" step="0.01" placeholder="Ecoacash USD Rate (Optional)" class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label for="mileage"></label>
                            <input type="number" name="mileage" id="mileage" placeholder="Mileage" class="form-control" required>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="plate_number"></label>
                            <input type="text" name="plate_number" id="plate_number" placeholder="Plate Number" class="form-control" required>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="model_year"></label>
                            <input type="number" name="model_year" id="model_year" placeholder="Model Year" class="form-control" required>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="id_fuel_type"></label>
                            <select name="fuel_type" class="form-control" required id="id_fuel_type">
                                <option value="" selected="">Fuel Type...</option>
                                <option value="Petrol">Petrol</option>
                                <option value="Diesel">Diesel</option>
                                <option value="Gas">Gas</option>
                                <option value="Hybrib">Hybrid</option>
                                <option value="Electric">Electric</option>
                            </select>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="color"></label>
                            <input type="text" name="color" id="color" placeholder="Color" class="form-control" required>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="num_seats"></label>
                            <input type="number" name="num_seats" id="num_seats" placeholder="Number of Seats" class="form-control" required>
                        </div>

                        <div class="form-group col-md-12">
                            <label for="description"></label>
                            <input type="text" name="description" id="description" max_length="100" placeholder="Description" class="form-control" required>
                        </div>
                    </div>
                </div>


                <p class="errors">{{form.errors}}<p>
     
                <div class="buttons">
                <a href="{% url 'dash' %}"><button type="submit" class="btn btn-primary" style="padding-right: 1em; margin-right: 12px;">Add Car</button></a>
                 
                <a href="{% url 'dash' %}"><button type="button" style="padding-left: 1em;" class="btn btn-secondary">Cancel</button></a>
                </a>

                <br>
            </div>
            </form>
        </div>
    </div>
</div>
<script src="/static/js/car_add.js"></script>
</body>
{% endblock %}

car_owner/templates/car_update.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="/static/css/car_update.css">

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h1 class="head text-center">Edit : {{ car }}</h1>
        <hr>
      <form action="" method="POST">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.image.id_for_label }}">Image</label>
              {{ form.image }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.make.id_for_label }}">Make</label>
              {{ form.make }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.car_model.id_for_label }}">Car Model</label>
              {{ form.car_model }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.daily_rental_price.id_for_label }}">Daily Rental Price</label>
              {{ form.daily_rental_price }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.late_return_fee_per_hr.id_for_label }}">Late Return Fee per Hour</label>
              {{ form.late_return_fee_per_hr }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.ecocash_rate.id_for_label }}">Ecocash Rate</label>
              {{ form.ecocash_rate }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.plate_number.id_for_label }}">Plate Number</label>
              {{ form.plate_number }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.mileage.id_for_label }}">Mileage</label>
              {{ form.mileage }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.model_year.id_for_label }}">Model Year</label>
              {{ form.model_year }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.fuel_type.id_for_label }}">Fuel Type</label>
              {{ form.fuel_type }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.color.id_for_label }}">Color</label>
              {{ form.color }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="{{ form.num_seats.id_for_label }}">Number of Seats</label>
              {{ form.num_seats }}
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="{{ form.description.id_for_label }}">Description</label>
              {{ form.description }}
            </div>
          </div>
        </div>
        <div class="text-center">
          <input type="submit" value="Edit" class="btn btn-primary col-md-12">
{% endblock %}

car_owner/templates/edit_car.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="/static/css/edit_car.css">
<body>
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card-header">
            <h4 class="card-title">Edit Car</h4>
        </div>
        <div class="card-body">
            <form method="POST" action=" ">
                {% csrf_token %}

                <div class="row">
                    <div class="form-group imagefield col-md-6">
                        <label class="label" for="image">Image</label>
                        <div class="puput">
                        <input type="file" name="image" id="image" class="form-control-file" onchange="previewCarPhoto(event)">
                        </div>
                        <img src="{{car.image.url}}" alt="Car Photo Preview"  value="car.image.url" class="car-preview img-thumbnail" id="car-photo-preview" style="display: none">
                    </div>

                        <div class="form-group col-md-6">
                            <label class="label" for="make">Make</label>
                            <input type="text" name="make" value="{{car.make}}" id="make" maxlength="50"  class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label  class="label" for="car_model">Model</label>
                            <input type="text" name="car_model" value="{{car.car_model}}" id="car_model"  class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label class="label" for="daily_rental_price">Daily rental price</label>
                            <input type="number" name="daily_rental_price" value="{{car.daily_rental_price}}" id="daily_rental_price" step="0.01"  maxlength="50"  class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label class="label"  for="late_return_fee_per_hr">Late return fee per hour</label>
                            <input type="number" name="late_return_fee_per_hr" value="{{car.late_return_fee_per_hr}}" id="late_return_fee_per_hr" step="0.01"  class="form-control">
                        </div>
               
                        <div class="form-group col-md-6">
                            <label class="label"  for="ecoacash_rate">Ecocash Rate(Optional)</label>
                            <input type="number" name="ecoacash_rate" value="{{car.ecocash_rate}}" id="ecoacash_rate" step="0.01" class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label class="label" for="mileage">Mileage</label>
                            <input type="number" name="mileage" value="{{car.mileage}}" id="mileage" class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label class="label" for="plate_number">Plate Number</label>
                            <input type="text" name="plate_number" value="{{car.plate_number}}" id="plate_number" class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label class="label" for="model_year">Model Year</label>
                            <input type="number" name="model_year" value="{{car.model_year}}" id="model_year" class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label class="label" for="id_fuel_type">Fuel Type...</label>
                            <select name="fuel_type" class="form-control" value="{{car.fuel_type}}" id="id_fuel_type">
                                <option value="" selected="">{{car.fuel_type}}</option>
                                <option value="Petrol">Petrol</option>
                                <option value="Diesel">Diesel</option>
                                <option value="Gas">Gas</option>
                                <option value="Hybrib">Hybrid</option>
                                <option value="Electric">Electric</option>
                            </select>
                        </div>

                        <div class="form-group col-md-6">
                            <label class="label" for="color">Color</label>
                            <input type="text" name="color" value="{{car.color}}" id="color" class="form-control">
                        </div>

                        <div class="form-group col-md-6">
                            <label class="label" for="num_seats">Number of Seats</label>
                            <input type="number" name="num_seats" value="{{car.num_seats}}" id="num_seats" class="form-control" >
                        </div>

                        <div class="form-group col-md-12">
                            <label class="label" for="description">Description</label>
                            <input type="text" name="description" id="description" value="{{car.description}}" max_length="100" class="form-control">
                        </div>
                    </div>

                <input type="submit" value="edit" class="btn btn-secondary">
                <a href="{% url 'dash' %}"><button type="button" style="padding-left: 1em;" class="btn btn-secondary">Cancel</button></a>
            </div>
            </form>
        </div>
    </div>
</div>
<script src="/static/js/edit_car.js"></script>
</body>

{% endblock %}

car_owner/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}   
<link rel="stylesheet" href="/static/css/edit_profile.css">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">Edit Profile</div>
          <div class="card-body">
            <form method="POST" action="{% url 'profile_edit' %}" enctype="multipart/form-data">
              {% csrf_token %}

              <div class="profile-pic">
                <label for="id_profile_pic">Profile Picture</label>
                <img src="{% if form.profile_pic.value %}
                              {{ form.profile_pic.value.url }}
                            {% else %}
                              static/media/user_prof_pic/default_prof_pic.png
                            {% endif %}" alt="Profile Picture">
                <input type="file" name="profile_pic" id="id_profile_pic" accept="image/*">
                <button type="button" class="btn btn-primary" onclick="document.getElementById('id_profile_pic').click()">Select Picture</button>
              </div>

              <div class="form-group">
                <label class="form-label" for="{{ form.phone_number.id_for_label }}">Phone Number</label>
                {{ form.phone_number }}
              </div>

              <div class="form-group">
                <label class="form-label" for="{{ form.city.id_for_label }}">City</label>
                {{ form.city }}
              </div>

              <div class="form-group">
                <label class="form-label" for="{{ form.address.id_for_label }}">Address</label>
                {{ form.address }}
              </div>

              <button type="submit" class="btn btn-primary">Save Profile</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

car_owner/templates/owner_form.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <h2 class="my-4">Wanna get your car rented ?</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form}}
            <button class="btn btn-primary my-4" type="submit">Submit</button>
    </form>
</div>

{% endblock %}

car_owner/templates/update_cars.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="/static/css/update_cars.css">
  <center>
    <br>
    <h1>{{car.make}} Update</h1>
    <form action=" " method="POST">
        {% csrf_token %}
        
        <div class="row">
            <div class="form-group imagefield col-md-6">
                <div class="current-image">
                Current: <a href="{{car.image.url}}">Image</a>
                <img class="img-thumbnail fit-image" src="{{ car.image.url }}" alt="Card image cap">
                <br>
            </div>
                <input type="file" name="image" accept="image/*" id="id_image">
                <img src="/media/static/media/cars/images/810fbaa1-4989-4173-9a50-de72c0035f68_83vYFzD.jpeg" alt="Car Photo Preview" value="car.image.url" class="car-preview img-thumbnail" id="car-photo-preview" style="display: none">
                
            </div>

            <div id="make" class="form-group col-md-6">
                <label class="label" for="make">Make</label>
                {{form.make}}
            </div>

            <div class="form-group col-md-6">
                <label  class="label" for="car_model">Model</label>
                {{form.car_model}}
            </div>

            <div class="form-group col-md-6">
                <label class="label" for="daily_rental_price">Daily rental price</label>
                {{form.daily_rental_price}}
            </div>

            <div class="form-group col-md-6">
                <label class="label"  for="late_return_fee_per_hr">Late return fee per hour</label>
                {{form.late_return_fee_per_hr}}
            </div>

            <div class="form-group col-md-6">
                <label class="label"  for="ecoacash_rate">Ecocash Rate(Optional)</label>
                {{form.ecocash_rate}}
            </div>

            <div class="form-group col-md-6">
                <label class="label" for="mileage">Mileage</label>
                {{form.mileage}}
            </div>
            <div class="form-group col-md-6">
                <label class="label" for="plate_number">Plate Number</label>
                {{form.plate_number}}
            </div>

            <div class="form-group col-md-6">
                <label class="label" for="model_year">Model Year</label>
                {{form.model_year}}"
            </div>

            <div class="form-group col-md-6">
                <label class="label" for="id_fuel_type">Fuel Type...</label>
                {{form.fuel_type}}
            </div>

            <div class="form-group col-md-6">
                <label class="label" for="color">Color</label>
                {{form.color}}
            </div>

            <div class="form-group col-md-6">
                <label class="label" for="num_seats">Number of Seats</label>
                {{form.num_seats}}
            </div>

            <div id="disc" class="form-group col-md-6">
                <label class="label" for="description">Description</label>
                {{form.description}}
            </div>
            </div>
            <br/>
        <input type="submit" value="update" class="btn btn-secondary">
        <a href="{% url 'dash' %}"><button type="button" style="padding-left: 1em;" class="btn btn-secondary">Cancel</button></a>
        {% for message in messages %}
            <p id="messages">{{message}}</p>
        {% endfor %}
    </form>
    
  </center>
{% endblock %}