car_rental/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from home.views import (
    landingpage
)

urlpatterns = [
    path('', landingpage, name='landingpage'),
    path('', include("cars.urls")),
    path('', include("chauffeur.urls")),
    path('', include("rental.urls")),
    path('', include("car_owner.urls")),
    path('', include("user.urls")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path, include
from .views import UpdateCarLikes
from . import views

urlpatterns = [
    path("car_list/", views.all_cars, name="car_list"),
    path("car/<int:pk>/", views.car_detail, name="car_detail"),
    path("photo/<int:pk>/", views.photo, name="photo"),
    path("car/<int:pk>/save/", views.save_car, name="save-car"),
    path("saved_car_list/", views.user_saved_cars, name="saved-cars"),
    path("car/<int:pk>/remove/", views.remove_car, name="remove-car"),
    path(
        "car_review/<int:car_id>/<str:review>",
        UpdateCarLikes.as_view(),
        name="car_review",
    ),
    path("car/<int:car_id>/remove/", views.remove_car, name="remove_from_saved"),
    path("index/", views.index, name="index"),
    path("search_cars/", views.search_cars, name="search_cars"),
    path("filter_car/", views.car_filter, name="car-filter"),
]

chauffeur/urls.py
from django.urls import path
from .views import ChauffeurUpdateView
from . import views


urlpatterns = [
    path("add_chauffeur", views.chauffeur_add, name="add_chauffeur"),
    path("chauffeur_list", views.chauffeur_list, name="chauffeur_list"),
    path(
        "chauffeur_rental_history",
        views.chauffuer_rental_history,
        name="chauffeur_rental_history",
    ),
    path("chauffeur_reciept", views.chauffeur_reciept, name="chauffeur_reciept"),
    path(
        "chauffeur_edit/<int:pk>/", ChauffeurUpdateView.as_view(), name="chauffeur_edit"
    ),
]

rental/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('booking/<int:pk>/', views.book_car, name='booking_form'),
    path('booking/<int:pk>/confirm/', views.booking_confirmation, name='booking_confirmation'),
    path('booking_form/chauffeurs/', views.chauffeur_list, name='choose_chauffeur_list'),
    path("rental/<int:pk>/", views.rental_details, name="rental_detail"),
    path("rental_history/", views.rental_history, name="rental_history"),
    path("reciept/", views.generate_reciept, name="generate_reciept"),
]

chauffeur/models.py
from django.utils import timezone
from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal
from user.models import CustomUser


class Chauffeur(models.Model):
    id = models.AutoField(primary_key=True)
    driver = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)
    profile_photo = models.ImageField(
        upload_to="static/media/chauffeur_profiles", blank=False
    )
    first_name = models.CharField(max_length=50, null=False, blank=False, default=None)
    last_name = models.CharField(max_length=50, null=False, blank=False, default=None)
    phone_number = models.IntegerField(default="+263")
    email = models.EmailField(blank=False, default=None)
    daily_fee = models.DecimalField(
        decimal_places=2,
        max_digits=6,
        default=Decimal("0.00"),
    ) 
    driver_experience = models.PositiveIntegerField(default=None)
    ecocash_rate = models.DecimalField(
        default=Decimal("0.00"), max_digits=7, decimal_places=2
    )
    is_booked = models.BooleanField(default=False)
    rating = models.FloatField(
        default=0.0,
        validators=[
            MinValueValidator(0.0),
        ],
    )
    date_joined = models.DateTimeField(default=timezone.now)

rental/models.py
from decimal import Decimal
from django.db import models
from cars.models import Car
from django.urls import reverse
from user.models import CustomUser
from chauffeur.models import Chauffeur


class Rental(models.Model):
    RENTAL_STATUS = [
        ("In Progress", "In Progress"),
        ("Completed", "Completed"),
    ]

    PAYMENT_METHOD_CHOICES = [("Ecocash", "Ecocash"), ("USD", "USD")]
   
    id = models.AutoField(null=False, primary_key=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, default=None)
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    payment_method = models.CharField(
        max_length=50,
        null=False,
        blank=False,
        choices=PAYMENT_METHOD_CHOICES,
        default="USD",
    )
    chauffeur = models.ForeignKey(
        Chauffeur, on_delete=models.CASCADE, default=None, null=True, blank=True
    )
    with_chauffeur = models.BooleanField(default=False)
    customer_destination = models.CharField(max_length=100, blank=False, default=None)
    status = models.CharField(max_length=100, choices=RENTAL_STATUS, default=None)
    is_returned = models.BooleanField(default=False)
    return_date = models.DateField(blank=True, null=True)
    rental_cost = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0
    )
    late_return_fee = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)

    #def calculate_rental_fee(self):
     #   rental_days = (self.end_date - self.start_date).days + 1
      #  if self.car.ecocash_rate and self.payment_method == "Ecocash":
       #     rental_fee = (
        #        self.car.daily_rental_price * rental_days * self.car.ecocash_rate
         #   )
        #elif self.chauffeur.ecocash_rate and self.payment_method == "Ecocash":
         #   if self.with_chauffeur:
          #      rental_fee = self.car.daily_rental_price * self.car.ecocash_rate + (
           #         self.chauffeur.ecocash_rate * self.chauffeur.daily_fee
            #    )
        #elif self.payment_method == "USD" and self.with_chauffeur:
         #   rental_fee = rental_days * (
          #      self.car.daily_rental_price + self.chauffeur.daily_fee
           # )
        #else:
         #   rental_fee = self.car.daily_rental_price * rental_days
        #return rental_fee

    # def calculate_grand_total(self, payment_method):
    #    rental_fee = self.calculate_rental_fee()
    #    if self.return_date and self.return_date > self.end_date:
    #        late_return_fee = self.car.late_return_fee_per_hr * (
    #                (self.return_date - self.end_date).seconds // 3600
    #            )

    #    elif self.return_date and self.return_date > self.end_date:
    #        if self.payment_method == 'Ecocash':
    #            late_return_fee =  self.car.ecocash_rate * (
    #                                            self.car.late_return_fee_per_hr *
    #                                            ((self.return_date - self.end_date).seconds // 3600)
    #                                        )
    #            total = late_return_fee + rental_fee
    #    return total

    def get_absolute_url(self):
        return reverse("rental_detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.customer.username} rented {self.car.make} {self.car.car_model}"


class RentalHistory(models.Model):
    car_owner = models.CharField(max_length=100, default=None, blank=False)
    customer = models.ForeignKey(
        CustomUser, on_delete=models.PROTECT, blank=False, default=None
    )
    chauffeur = models.ForeignKey(Chauffeur, on_delete=models.PROTECT)
    car = models.ForeignKey(Car, on_delete=models.PROTECT, default=None, blank=False)
    rental_days = models.IntegerField(blank=False, default=None)
    chauffeurs_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    rental_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

chauffeur/forms.py
from django import forms
from .models import Chauffeur


class ChauffeurForm(forms.ModelForm):
    class Meta:
        model = Chauffeur
        fields = [
            "profile_photo",
            "first_name",
            "last_name",
            "phone_number",
            "email",
            "driver_experience",
            "ecocash_rate",
            "daily_fee",
        ]

rental/forms.py
from django import forms
from django.utils import timezone
from .models import Rental


class RentalForm(forms.ModelForm):
    start_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    end_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    payment_method = forms.ChoiceField(
        choices=[("USD", "USD"), ("Ecocash", "Ecocash")], widget=forms.RadioSelect
    )
    customer_destination = forms.CharField(max_length=100, required=True)
    with_chauffeur = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    
    def clean(self):
        cleaned_data = super().clean()

        start_date = cleaned_data.get('start_date')
        if start_date:
            cleaned_data['start_date'] = start_date.replace(tzinfo=None).isoformat()

        end_date = cleaned_data.get('end_date')
        if end_date:
            cleaned_data['end_date'] = end_date.replace(tzinfo=None).isoformat()

        return cleaned_data

    class Meta:
        model = Rental
        fields = [
            "start_date",
            "end_date",
            "with_chauffeur",
            "customer_destination",
            "payment_method",
        ]

chauffeur/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from cars.models import Car
from rental.models import Rental
from .models import Chauffeur
from .forms import ChauffeurForm
from django.views.generic import ListView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView


def chauffeur_add(request):
    if request.method == "POST":
        form = ChauffeurForm(request.POST, request.FILES)
        if form.is_valid():
            chauffeur = form.save(commit=False)
            chauffeur.driver = request.user
            chauffeur.save()
            messages.success("Chauffeur added successfully")
            return redirect("chauffeur_dashboard")
    else:
        form = ChauffeurForm()
    return render(request, "chauffeur/chauffeur_add.html", {"form": form})


class ChauffeurUpdateView(LoginRequiredMixin, UpdateView):
    model = Chauffeur
    form_class = ChauffeurForm
    template_name = "chauffeur/edit_chauffeur.html"
    success_url = reverse_lazy("profile")


def chauffeur_list(request):
    chauffeurs = Chauffeur.objects.all()
    context = {"chauffeurs": chauffeurs}
    return render(request, "chauffeur/chauffeurs.html", context)


def chauffeur_reciept(request):
    # context = {}
    return render(request, "chauffeur/chauffuer_reciept.html")


def chauffuer_rental_history(request):
    # context = {}
    return render(request, "chauffeur/chauffeur_rental_history.html")

rental/views.py
import datetime
from datetime import timedelta
from django.shortcuts import render
from django.views import View
from django.views.generic import CreateView
from .models import Rental, Chauffeur
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DeleteView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from .forms import RentalForm
from payments.models import Payment
from .models import Car, Rental, RentalHistory
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.conf import settings
from django.urls import reverse
from .forms import RentalForm
from django.http import HttpResponse


def book_car(request, pk):
    car = get_object_or_404(Car, pk=pk)
    if request.method == "POST":
        form = RentalForm(request.POST)
        if form.is_valid():
            booking_data = form.cleaned_data
            # store data in in a seesion
            request.session["booking_data"] = booking_data
            with_chauffeur = booking_data.get('with_chauffeur')
            if with_chauffeur:
                return redirect('choose_chauffeur_list')
            else:
                return redirect('booking_confirmation', pk=car.pk)
    else:
        form = RentalForm()
    return render(request, "rental/rental_form.html", {"car": car, "form": form})


def booking_confirmation(request, pk):
    car = get_object_or_404(Car, pk=pk)
    rental = None
    chauffeur_id = request.POST.get(Chauffeur.id)
        # Retrieve the stored booking data from the session
    booking_data = request.session.get("booking_data")
    if booking_data:
        chauffeur_present = booking_data.get("with_chauffeur")
        chauffeur = None
        if chauffeur_present:
            chauffeur = get_object_or_404(Chauffeur, id=chauffeur_id)
            booking_data["chauffeur"] = chauffeur
            price = car.ecocash_rate * (car.daily_rental_price + chauffeur.daily_fee)
        else:
            price = car.ecocash_rate * car.daily_rental_price

            # Send an email to the chauffeur
            # send_email_to_chauffeur(booking_data, car, chauffeur) 
        

        rental = Rental(
            car=car,
            customer = request.user,
            start_date=booking_data["start_date"],
            end_date=booking_data["end_date"],
            customer_destination=booking_data["customer_destination"],
            payment_method=booking_data["payment_method"],
            with_chauffeur=bool(chauffeur_id),
            rental_cost=price,
            chauffeur=chauffeur if chauffeur_present else None, 
            status = "Completed"  
        )
        rental.save()
        # Clear the booking data from the session
        del request.session["booking_data"]
        return redirect("rental_detail", pk=rental.pk)

    else:
        messages.success(request, "Just rendered your rental details")
        return render(request, "rental/booking_confirmation.html", {"car": car, "rental": rental})
   

def chauffeur_list(request):
    chauffeurs = Chauffeur.objects.all()
    context = {"chauffeurs": chauffeurs}
    return render(request, "rental/chauffeurs.html", context)

def rental_details(request, pk):
    rental = get_object_or_404(Rental, pk=pk)
    return render(request, "rental/rental_details.html", {"rental": rental})


def generate_reciept(request):
    # context = {}
    return render(request, "rental/rental_reciept.html")


def rental_history(request):
    # context ={}
    return render(request, "rental/rental_records.html")

rental/templates/booking_confirmation.html
<!-- booking_confirmation.html -->
<h2>Booking Confirmation</h2>
<h3>Car: {{ rental.car.make }}</h3>
<p>Start Date: {{ rental.start_date }}</p>
<p>End Date: {{ rental.end_date }}</p>

{% if booking_data.chauffeur %}
  <p>Chauffeur: {{ booking_data.chauffeur.first_name }}</p>
{% endif %}

<p>Price: {{ rental.rental_cost }}</p>

<!-- Proceed to payment button -->
<a href="{#% url 'payment' car.id %#}" class="btn btn-primary">Proceed to Payment</a> 

rental/templates/chauffeurs.html
{% extends 'base.html' %}
<!-- chauffeur_list.html -->
{% block content %}
<h2>Chauffeur Selection</h2>
<h3>Car: {{ car.make }}</h3>

<form method="POST" action="">
  {% csrf_token %}

  <!-- Display list of available chauffeurs -->
  {% for chauffeur in chauffeurs %}
    <label>
      <input type="radio" name="chauffeur" value="{{ chauffeur.id }}">
      {{ chauffeur.first_name }}
    </label><br>
  {% endfor %}

  <a href="{% url 'booking_confirmation' car.pk %}"> <button type="submit" class="btn btn-primary">Continue</button></a>
</form>
{% endblock  %}

rental/templates/rental_details.html
{% extends 'base.html' %}

{% block content %}
<section class="vh-100" style="background-color: #35558a;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100 text-center">
      <div class="col">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-light btn-lg" data-mdb-toggle="modal"
          data-mdb-target="#exampleModal">
          <i class="fas fa-info me-2"></i> Get rental detail information
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
          aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header border-bottom-0">
                <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body text-start text-black p-4">
                <h5 class="modal-title text-uppercase mb-5" id="exampleModalLabel">{{ rental.car.make }} <strong>{{ rental.car.car_model }}</strong></h5>
                <h4 class="mb-5" style="color: #35558a;">Thanks for your booking</h4>
                <p class="mb-0" style="color: #35558a;">Rental summary</p>
                <hr class="mt-2 mb-4"
                  style="height: 0; background-color: transparent; opacity: .75; border-top: 2px dashed #9e9e9e;">

                <div class="d-flex justify-content-between">
                  <p class="fw-bold mb-0">Customer</p>
                  <p class="text-muted mb-0">{{rental.customer}}</p>
                </div>

                <div class="d-flex justify-content-between">
                  <p class="fw-bold mb-0">Car Owner</p>
                  <p class="text-muted mb-0">{{rental.car.owner}}</p>
                </div>

                <div class="d-flex justify-content-between">
                  <p class="small mb-0">Start-date</p>
                  <p class="small mb-0">{{rental.start_date}}</p>
                </div>

                <div class="d-flex justify-content-between pb-1">
                  <p class="small">End-date</p>
                  <p class="small">{{rental.end_date}}</p>
                </div>

                {% if rental.chauffeur %}
                <div class="d-flex justify-content-between pb-1">
                  <p class="small">Driver</p>
                  <p class="small">{{rental.chauffeur.name}}</p>
                </div>
                {% else %}
                <div class="d-flex justify-content-between pb-1">
                  <p class="small">Driver Situation</p>
                  <p class="small">You did'nt select a chauffeur</p>
                </div>
                {% endif %}

                <div class="d-flex justify-content-between">
                  <p class="fw-bold">Rental Cost</p>
                  <p class="fw-bold" style="color: #35558a;">ZWL {{rental.rental_cost}}</p>
                </div>

              </div>
              <div class="modal-footer d-flex justify-content-center border-top-0 py-4">
                <button type="button" class="btn btn-primary btn-lg mb-1" style="background-color: #35558a;">
                  Proceed to payment
                </button>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>
{% endblock %}

rental/templates/rental_form.html
{% extends 'base.html' %}
<link rel="stylesheet" href="/static/css/rental_form.css">
{% block content %}
<br><br>

<div class="rental_form" style="display: flex; margin-left: 233px; @media (max-width: 600px){ margin-left: 23px;}">

    <div class="px-3" style= "@media (max-width: 600px){ margin-left: 23px, display:None;}">
        <h2 style="color: cornflowerblue; font-weight: bolder;"><p class="book" style="color: black;">Booking</p> {{ car.make }} {{ car.car_model }}</h2>
        <hr>
            <p class="small text-muted mb-1">Model Year</p>
            <p class="mb-0" style="color: cornflowerblue; font-weight: bolder;">{{ car.model_year }}</p>

            <p class="small text-muted mb-1">Daily Rental Price/Ecocash</p>
            {% if car.ecocash_rate %}
                <p class="mb-0" style="color: cornflowerblue; font-weight: bolder;">ZWL{{car.ecocash_rate}}</p>
            {% else %}
                <p class="mb-0" style="color: cornflowerblue; font-weight: bolder;">${{car.daily_rental_price}}</p>
            {% endif %}

            <p class="small text-muted mb-1">Car Owner</p>
            <p class="mb-0" style="color: cornflowerblue; font-weight: bolder;">@{{car.owner.username}}</p>

            <p class="small text-muted mb-1">Car Color</p>
            <p class="mb-0" style="color: cornflowerblue; font-weight: bolder;">{{car.color}}</p>

            <p class="small text-muted mb-1">Late Return Fee</p>
            <p class="mb-0" style="color: cornflowerblue; font-weight: bolder;">${{car.late_return_fee_per_hr}}/hr</p>

            {% for message in messages%}
                <p style="color:red;">{{messages}}</p>
            {% endfor %}
    </div>




    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
      
                <form method="post">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="id_start_date">Start Date</label>
                        {{ form.start_date }}
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="id_end_date">End Date</label>
                        {{ form.end_date }}
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="id_with_chauffeur">With Chauffeur</label>
                        {{ form.with_chauffeur }}
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="id_customer_destination">Customer Destination</label>
                        {{ form.customer_destination }}
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="id_payment_method">Payment Method</label>
                        {{ form.payment_method }}
                    </div><br>
                    <button type="submit" class="btn btn-primary">Proceed</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

rental/templates/rental_reciept.html
<h1>Rental Recipts</h1>
<section class="h-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-10 col-xl-8">
          <div class="card" style="border-radius: 10px;">
            <div class="card-header px-4 py-5">
              <h5 class="text-muted mb-0">Thanks for your Order, <span style="color: #a8729a;">Anna</span>!</h5>
            </div>
            <div class="card-body p-4">
              <div class="d-flex justify-content-between align-items-center mb-4">
                <p class="lead fw-normal mb-0" style="color: #a8729a;">Receipt</p>
                <p class="small text-muted mb-0">Receipt Voucher : 1KAU9-84UIL</p>
              </div>
              <div class="card shadow-0 border mb-4">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-2">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/13.webp"
                        class="img-fluid" alt="Phone">
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0">Samsung Galaxy</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">White</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">Capacity: 64GB</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">Qty: 1</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">$499</p>
                    </div>
                  </div>
                  <hr class="mb-4" style="background-color: #e0e0e0; opacity: 1;">
                  <div class="row d-flex align-items-center">
                    <div class="col-md-2">
                      <p class="text-muted mb-0 small">Track Order</p>
                    </div>
                    <div class="col-md-10">
                      <div class="progress" style="height: 6px; border-radius: 16px;">
                        <div class="progress-bar" role="progressbar"
                          style="width: 65%; border-radius: 16px; background-color: #a8729a;" aria-valuenow="65"
                          aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <div class="d-flex justify-content-around mb-1">
                        <p class="text-muted mt-1 mb-0 small ms-xl-5">Out for delivary</p>
                        <p class="text-muted mt-1 mb-0 small ms-xl-5">Delivered</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card shadow-0 border mb-4">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-2">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/1.webp"
                        class="img-fluid" alt="Phone">
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0">iPad</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">Pink rose</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">Capacity: 32GB</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">Qty: 1</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">$399</p>
                    </div>
                  </div>
                  <hr class="mb-4" style="background-color: #e0e0e0; opacity: 1;">
                  <div class="row d-flex align-items-center">
                    <div class="col-md-2">
                      <p class="text-muted mb-0 small">Track Order</p>
                    </div>
                    <div class="col-md-10">
                      <div class="progress" style="height: 6px; border-radius: 16px;">
                        <div class="progress-bar" role="progressbar"
                          style="width: 20%; border-radius: 16px; background-color: #a8729a;" aria-valuenow="20"
                          aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <div class="d-flex justify-content-around mb-1">
                        <p class="text-muted mt-1 mb-0 small ms-xl-5">Out for delivary</p>
                        <p class="text-muted mt-1 mb-0 small ms-xl-5">Delivered</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
  
              <div class="d-flex justify-content-between pt-2">
                <p class="fw-bold mb-0">Order Details</p>
                <p class="text-muted mb-0"><span class="fw-bold me-4">Total</span> $898.00</p>
              </div>
  
              <div class="d-flex justify-content-between pt-2">
                <p class="text-muted mb-0">Invoice Number : 788152</p>
                <p class="text-muted mb-0"><span class="fw-bold me-4">Discount</span> $19.00</p>
              </div>
  
              <div class="d-flex justify-content-between">
                <p class="text-muted mb-0">Invoice Date : 22 Dec,2019</p>
                <p class="text-muted mb-0"><span class="fw-bold me-4">GST 18%</span> 123</p>
              </div>
  
              <div class="d-flex justify-content-between mb-5">
                <p class="text-muted mb-0">Recepits Voucher : 18KU-62IIK</p>
                <p class="text-muted mb-0"><span class="fw-bold me-4">Delivery Charges</span> Free</p>
              </div>
            </div>
            <div class="card-footer border-0 px-4 py-5"
              style="background-color: #a8729a; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;">
              <h5 class="d-flex align-items-center justify-content-end text-white text-uppercase mb-0">Total
                paid: <span class="h2 mb-0 ms-2">$1040</span></h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

rental/templates/rental_records.html
<h1>Rental History</h1>